### ISSUE TITLE
Can't install version 1.0.6

### ISSUE THREAD

**Issue by PranKe01** [freeletics/FLTextView#20]
Hi,
in my podfile I have the following entry:
pod 'FLTextView', '~> 1.0.6'
Error: None of your spec sources contain a spec satisfying the dependency.

Then I tried:
pod 'FLTextView', :git => 'https://github.com/freeletics/FLTextView.git', :tag => '1.0.6'
Error: Unable to find specifiation for FLTextView.

Then I tried what stands in the documentation:
pod 'FLTextView', '~> 1.0'
This installed version 1.0.2 :(

How to install the version 1.0.6? Maybe the documentation could be updated...

**Comment by catalinaturlea** [comment]
@PranKe01 should be fixed now. Thanks for using it and letting us know

**Comment by PranKe01** [comment]
Nope, still doesn't work. I made a repo update, but still does not work with:
pod 'FLTextView', '~> 1.0.6'

And on cocoapods there is still v1.0.2 listed: https://cocoapods.org/pods/FLTextView

**Comment by catalinaturlea** [comment]
@PranKe01  please try like this pod 'FLTextView', :git => 'https://github.com/freeletics/FLTextView.git', :tag => '1.0.6'
we are unable to update the podspec on the main repo for now
